service: kids-hosting
image: willcosgrove/kids-hosting

registry:
  username: willcosgrove
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: arm64
  remote: mini.local

proxy:
  ssl: false
  hosts:
    - graham.cosgrove.kids
    - caroline.cosgrove.kids

ssh:
  user: will

servers:
  web:
    hosts:
      - mini.local
    options:
      publish:
        - 2222:2222

volumes:
  - /var/www/kids-sites:/sites

env:
  secret:
    - GRAHAM_PASSWORD
    - CAROLINE_PASSWORD
